name: Rubocop
on:  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7']

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: bundler exec rspec spec/*

      - name: Run rubocop
        run: bundle exec rubocop --parallel
