name: Spec Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  spec_coverage:
    name: Spec Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1.0']

    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1'
      - name: Bundle install
        run: bundle install
      - name: Run simplecov
        run: COVERAGE=True bundle exec rspec
